### ISSUE TITLE
How does export work? How to set a realm to optimise for?

### ISSUE THREAD

**Issue by BaconCatBug** [Menencia/ffrk-io#2]
When I press export, nothing happens. I also cannot see anywhere to set a realm.

**Comment by Menencia** [comment]
After clicking on export, you should see a popup displaying a textarea with the data. If you don't see it, it's a bug, can you tell me which browser are you using?
Also, there's no current realm option. Each synergy stat are calculated for the item onto his own realm. Would it be interesting to set up a "current realm" option ?

**Comment by BaconCatBug** [comment]
I am using Google Chrome Version 43.0.2357.124 m. I tried without any
plugins also to check if it was them interfering and it happens without
too.

As for selecting realm, don't worry about it. I was thinking of something
else. :P Something like how Item Keeper did that showed you the top 6
weapons for each realm or something.

**Comment by Menencia** [comment]
Well actually, the best way is to order by realm then compare by synergy stats.
And about the export bug, i let you know if I find anything...

**Comment by Menencia** [comment]
Export bug has been fixed, btw.
